import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { GetStaticProps, NextPage } from "next";
import { Character } from "../types/Character";
import axiosClient from "@/service/client";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

const Home: NextPage<{ characters: Character[] }> = ({ characters }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {characters.map((character) => (
          <div key={character.id}>
            <Image
              src={character.image}
              alt="Character"
              height={200}
              width={200}
            />
            <Link href={`/characters/${character.id}`}>
                <p>{character.name}</p>
            </Link>
          </div>
        ))}
      </main>
    </>
  );
};

export const getStaticProps: GetStaticProps = async (context) => {
  const res = await axiosClient.get("/character");
  const results: Character[] = res.data.results;
  return {
    props: {
      characters: results,
    },
  };
};

export default Home;
